### ISSUE TITLE
Provide minimal supported Ansible version

### ISSUE THREAD

**Issue by przmv** [tidalmigrations/machine_stats#71]
Right now Machine Stats for Unix-like Systems requires `ansible<2.10` (because 2.10 is not _yet_ [supported by Red Hat](https://access.redhat.com/articles/5392421)). However, the minimal required version is not specified. This leads to the following issue:

- OS: Debian 10 (buster)
- Ansible 2.7.7 (installed with `sudo apt-get install ansible`)
- Machine Stats 1.0.1 (installed with `pip3 install machine-stats`)

```console
$ machine-stats --help
Traceback (most recent call last):
  File "/home/petr_razumov/.local/bin/machine-stats", line 6, in <module>
    from machine_stats import main
  File "/home/petr_razumov/.local/lib/python3.7/site-packages/machine_stats/__init__.py", line 56, in <module>
    from ansible import context
ImportError: cannot import name 'context' from 'ansible' (/usr/lib/python3/dist-packages/ansible/__init__.py)
```

`ansible.context` was introduced in `v2.8.0`

**Comment by pranavmalaviya** [comment]
More details/discussion on this issue is being done internally in [this doc](https://docs.google.com/document/d/1S2HOPy8CaJFhVAZZR146slEG_Zxu5erYsKGS6f_iJtg/).
